"""empty message

Revision ID: 8a284baf731a
Revises: 832a047f514e
Create Date: 2016-04-12 21:48:58.502176

"""

# revision identifiers, used by Alembic.
revision = '8a284baf731a'
down_revision = '832a047f514e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('completed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'completed')
    ### end Alembic commands ###
